### ISSUE TITLE
Store test results to test project in Terarium

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/simulation-integration#21]
This will require specifying the test project id `102` and the TDS url (prod) for the GH action.

Note--we should test this on staging first (after local testing) to ensure we don't _gunk up (!!!)_ the now clean test project on prod

![Screenshot 2023-11-06 at 10 13 12 AM](https://github.com/DARPA-ASKEM/simulation-integration/assets/5840199/9c23d103-78a6-482c-8dab-eb26f3567326)

see above screenshot for how this is set up on KM

Note that the environment [has to be specified in the GH action YAML](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/.github/workflows/report.yaml#L13) and can then [be leveraged](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/.github/workflows/report.yaml#L58-L59)

**Comment by Sorrento110** [comment]
Current items to work out with automatic workflow generation from the sim-int harness:

- [ ] Models in ensemble workflows not being automatically assigned as the correct model.
- [ ] Extra default configs on model nodes
- [ ] Edges are not drawn correctly because offsets are difficult to calculate.
- [ ] No optimize nodes yet.
